config/routes.rb
KoudokuCoupons::Engine.routes.draw do
  
  resources :promotions
  
  get ":id" => 'promotions#show', :as => :default_route, :defaults => {id: ''}
end

app/models/koudoku_coupons/promotion.rb
module KoudokuCoupons
  class Promotion < ActiveRecord::Base
    attr_accessible :coupon_code, :name, :redirect
  end
end

app/controllers/koudoku_coupons/application_controller.rb
module KoudokuCoupons
  class ApplicationController < ActionController::Base
  end
end

app/controllers/koudoku_coupons/promotions_controller.rb
module KoudokuCoupons
  class PromotionsController < KoudokuCoupons::ApplicationController
    
    def index
      @promotions = Promotion.all
    end
    
    def new
      @promotion = Promotion.new
    end
    
    def create
      @promotion = Promotion.new(params[:promotion])
      
      respond_to do |format|
        if @promotion.save
          
          format.html { redirect_to promotions_path, notice: 'Promotion was successfully created.' }
          format.json { render json: @promotion, status: :created, location: @promotion}
        else
          format.html { render action: "new" }
          format.json { render json: @promotion.errors, status: :unprocessable_entity }
        end
      end
    end
    
    def destroy
      @promotion = Promotion.find(params[:id])
      @promotion.destroy
      redirect_to promotions_path
    end
    
    def edit
      @promotion = Promotion.find(params[:id])
    end
    
    def update
      @promotion = Promotion.find(params[:id])
      
      respond_to do |format|
        if @promotion.update_attributes(params[:promotion])
          format.html { redirect_to promotions_path, notice: 'Promotion was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @promotion.errors, status: :unprocessable_entity }
        end
      end
    end
    
    def show
      return redirect_to main_app.root_path, status: 302 if params[:id].nil? || params[:id] == ''
      @promotion = Promotion.find_by_name(params[:id])
      
      return redirect_to main_app.root_path, status: 302 if @promotion.nil?
      session[:koudoku_coupon_code] = @promotion.coupon_code
      redirect_to @promotion.redirect, status: 302
    end
  end
end

app/helpers/koudoku_coupons/application_helper.rb
module KoudokuCoupons
  module ApplicationHelper
    # returns TRUE if the controller belongs to KoudokuCoupons
    # false in all other cases, for convenience when executing filters 
    # in the main application
    def koudoku_coupons_controller?
      is_a? KoudokuCoupons::ApplicationController
    end
  end
end

app/views/koudoku_coupons/promotions/_form.html.haml
- #@promotion.new_record? ? uri = calendar_appointments_path : uri = calendar_appointment_path
= form_for(@promotion, {html: {:class => 'form-horizontal', role: 'form', id: 'promotion_form'}}) do |f|
  - if @promotion.errors.any?
    #error_explanation
      %h2= "#{pluralize(@promotion.errors.count, "error")} prohibited this promotion from being saved:"

      %ul
        -@promotion.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, placeholder: 'Promotion Name', length: 30
  .form-group
    = f.label :coupon_code, 'Coupon Code', :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :coupon_code, placeholder: 'Stripe Coupon Code', length: 30
  .form-group
    = f.label :redirect, 'Redirect URL', :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :redirect, placeholder: 'Redirection URL'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Create', {:class => 'btn btn-primary btn-small', id: 'promotion_submit'}

app/views/koudoku_coupons/promotions/edit.html.haml
.container
  .row
    .col-md-offset-1.col-md-10
      %h3 Edit Promotion
      = render partial: 'form'

app/views/koudoku_coupons/promotions/index.html.haml
.container
  .row
    .col-md-offset-1.col-md-10
      %table.table.table-bordered.table-condensed
        %tr
          %th Name
          %th Coupon Code
          %th Redirection Target
          %th 
        - @promotions.each do |promotion|
          %tr
            %td= promotion.name
            %td= promotion.coupon_code
            %td= promotion.redirect
            %td
              = link_to "Edit", edit_promotion_path(promotion)
              = link_to "Delete", promotion_path(promotion), method: 'DELETE'
      =link_to 'New Promotion', new_promotion_path, :class => 'btn btn-default'

app/views/koudoku_coupons/promotions/new.html.haml
.container
  .row
    .col-md-offset-1.col-md-10
      %h3 Create new Promotion
      = render partial: 'form'

app/views/layouts/koudoku_coupons/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KoudokuCoupons</title>
  <%= stylesheet_link_tag    "koudoku_coupons/application", :media => "all" %>
  <%= javascript_include_tag "koudoku_coupons/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>